### ISSUE TITLE
Add {GRDN}: {GUARDIAN}

### ISSUE THREAD

**Issue by KANDEMsama01** [evmoswap/default-token-list#1]
- [x ] I understand that token listing is not required to use the EvmoSwap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the EvmoSwap default token list.
- [ x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0x0A88F465eA5079C39d88EA796A018604E2C00d56
Token Name (from contract): GUARDIAN
Token Symbol (from contract): GRDN
Token Decimals (from contract): 16
EvmoSwap Pair Address of Token: 0x0350b8794CD37E2aF683286f065320586e584b99

Link to official Twitter account: https://twitter.com/EvmosGuardians?s=20&t=v93YULRUy8j2UOfosC5uWQ
Link to the official homepage of token: https://www.evmosguardians.io/
Link to Token Logo (120x120 PNG, Circular logo):
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by evLorne** [comment]
added!
